// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rmdwthtaffbhlfunybvp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJtZHd0aHRhZmZiaGxmdW55YnZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4NzMxODYsImV4cCI6MjA3NDQ0OTE4Nn0.2nrd3F-acLjeJ3JFlOvceKqn8IgrdJSjpuD60H1kluI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});